# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24fc373804e67ee19fe0f270aabab6b19c7e5b356911fa030558028ed72de967c06f9a20e773edc4e80c9c378fd3b5b23658be4adbe482a079fb51524d7ed278

test:
  secret_key_base: 4f68ce593adb792200e262210e929bbea28f091a66808cd3629461015d963d5f328b156cc8e64be49ad10fbf82aeefb0a4f12b26abf42fbd637d3a7ab54dab91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
